### ISSUE TITLE
issue with mongodb

### ISSUE THREAD

**Issue by ghost** [teal33t/poopak#6]
Hi,

Hope you are all well !

When I start **docker-compose up**, I have the following errors and 502 error on localhost.

```bash
panel-worker       | Traceback (most recent call last):
panel-worker       |   File "manage.py", line 4, in <module>
panel-worker       |     from web import app
panel-worker       |   File "/application/web/__init__.py", line 52, in <module>
panel-worker       |     client.crawler.users.insert({"_id": "admin", "password": pass_hash})
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 3182, in insert
panel-worker       |     check_keys, manipulate, write_concern)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 612, in _insert
panel-worker       |     bypass_doc_val, session)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 600, in _insert_one
panel-worker       |     acknowledged, _insert_command, session)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1492, in _retryable_write
panel-worker       |     return self._retry_with_session(retryable, func, s, None)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1378, in _retry_with_session
panel-worker       |     with self._get_socket(server, session) as sock_info:
panel-worker       |   File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
panel-worker       |     return next(self.gen)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1223, in _get_socket
panel-worker       |     self.__all_credentials, checkout=exhaust) as sock_info:
panel-worker       |   File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
panel-worker       |     return next(self.gen)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 1128, in get_socket
panel-worker       |     sock_info.check_auth(all_credentials)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 712, in check_auth
panel-worker       |     auth.authenticate(credentials, self)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 564, in authenticate
panel-worker       |     auth_func(credentials, sock_info)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 539, in _authenticate_default
panel-worker       |     return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 263, in _authenticate_scram
panel-worker       |     res = sock_info.command(source, cmd)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 613, in command
panel-worker       |     user_fields=user_fields)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 167, in command
panel-worker       |     parse_write_concern_error=parse_write_concern_error)
panel-worker       |   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
panel-worker       |     raise OperationFailure(msg % errmsg, code, response)
panel-worker       | pymongo.errors.OperationFailure: Authentication failed.
crawler-worker     | Traceback (most recent call last):
crawler-worker     |   File "manage.py", line 4, in <module>
crawler-worker     |     from web import app
crawler-worker     |   File "/application/web/__init__.py", line 52, in <module>
crawler-worker     |     client.crawler.users.insert({"_id": "admin", "password": pass_hash})
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 3182, in insert
crawler-worker     |     check_keys, manipulate, write_concern)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 612, in _insert
crawler-worker     |     bypass_doc_val, session)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 600, in _insert_one
crawler-worker     |     acknowledged, _insert_command, session)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1492, in _retryable_write
crawler-worker     |     return self._retry_with_session(retryable, func, s, None)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1378, in _retry_with_session
crawler-worker     |     with self._get_socket(server, session) as sock_info:
crawler-worker     |   File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
crawler-worker     |     return next(self.gen)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1223, in _get_socket
crawler-worker     |     self.__all_credentials, checkout=exhaust) as sock_info:
crawler-worker     |   File "/usr/local/lib/python3.6/contextlib.py", line 82, in __enter__
crawler-worker     |     return next(self.gen)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 1128, in get_socket
crawler-worker     |     sock_info.check_auth(all_credentials)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 712, in check_auth
crawler-worker     |     auth.authenticate(credentials, self)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 564, in authenticate
crawler-worker     |     auth_func(credentials, sock_info)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 539, in _authenticate_default
crawler-worker     |     return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/auth.py", line 263, in _authenticate_scram
crawler-worker     |     res = sock_info.command(source, cmd)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 613, in command
crawler-worker     |     user_fields=user_fields)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 167, in command
crawler-worker     |     parse_write_concern_error=parse_write_concern_error)
crawler-worker     |   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
crawler-worker     |     raise OperationFailure(msg % errmsg, code, response)
crawler-worker     | pymongo.errors.OperationFailure: Authentication failed.
```

**Comment by anoduck** [comment]
Have you updated to the most recent version on mongodb?
